#!/bin/bash

screen -dm -S sprayer -c "source sprayer/bin/activate; . env_setup_prev; python cat_sprayer"
screen -dm -S api -c ". ../cat_board/api/start_backend"
screen -dm -S react_app -c "cd ../cat_board; npm start"