#!/bin/bash


screen -dm bash -c "source sprayer/bin/activate; . env_setup_priv; python cat_sprayer.py"
screen -dm bash -c "cd ../cat_board; . api/start_backend"
screen -dm bash -c "cd ../cat_board; npm start"